### ISSUE TITLE
ローカルファイルを開いたとき

### ISSUE THREAD

**Issue by FujiwaraDaigo** [yoshinobc/PDF-Translator#16]
無理なお願いかもしれませんが，ローカルファイルを開いたときにも対応することはできませんか？
(ローカルpdfファイルのviewerとしてchromeを利用したとき)

**Comment by yoshinobc** [comment]
すみません．
コードのバグでローカルファイルに対応できていませんでした．
chrome拡張公開の審査期間の都合上，数日後に修正されたversionを公開します．

**Comment by yoshinobc** [comment]
version2.2が公開されました．
インストール後
1. chromeタブ右上の地球儀アイコンを右クリック
2. 拡張機能を管理をクリック
3. ファイルの URL へのアクセスを許可するにチェック
で開けるようになると思います．

**Comment by FujiwaraDaigo** [comment]
最新版でローカルファイルも問題なく見れるようになりました！ありがとうございます．
非常に素晴らしいツールですね，利用させていただきます．
