### ISSUE TITLE
訳文が途切れる問題に関して

### ISSUE THREAD

**Issue by nkawasaki** [yoshinobc/PDF-Translator#19]
私はプログラミング等の素人なので、アイデアは出せないのですが、使いにくいと感じたところがあるためコメントを残します。
訳文が、選択した原文のすぐ右横から始まるため、訳文の一部が見切れて読めません。
もし可能でしたら改善していただけると助かります。
![image](https://user-images.githubusercontent.com/67691905/86242341-87e11e00-bbdf-11ea-84c2-cd3ce7f6d915.png)

**Comment by yoshinobc** [comment]
ありがとうございます．
この問題は，現在改善しなければいけない最優先事項だと考えています．
まだ良いアルゴリスムは思いついていませんが，早急に対処をしていきます．

**Comment by yoshinobc** [comment]
この問題に対応しました．(https://github.com/yoshinobc/DeepL-Translator-for-PDF/commit/1e6e3bce42aba261cf0d8d573156560e580f04a7)
翻訳結果の表示位置ができるだけ画面の外側にいかないように修正しました．
また，オプションページからwindowの下側に翻訳結果を表示するように変更できるようになりました．
<img width="716" alt="under" src="https://user-images.githubusercontent.com/33712536/86275784-c9d58880-bc0e-11ea-9e86-a6322ad8f56c.png">
