### ISSUE TITLE
Cannot move the translated window on screen??

### ISSUE THREAD

**Issue by K-PTL** [yoshinobc/PDF-Translator#20]
Hi @yoshinobc , thanks for sharing great chrome extension!!

How can I adjust the location of pop-up window by DeepL??
I can use this extension for my local PDF files, but I faced the critically inconvenient issue.
When i wanna translate sentences on chrome app, I selected them and deepl tab will be launched, after that, translation result window will be displayed next to the selected area. Often the window, however, beyond the edges of PC's screen (visible area), and I can't read full translated text. 

(日本語で簡単に：選択して翻訳はできます、しかしながらその翻訳された結果を表示するポップアップウィンドウが画面から見切れてしまうことが多いです。そのため、翻訳結果を全て確認できません。自動でchromeのwindow内に収まるようにするか、ウィンドウをマウスで移動できるようにするか、の対応が欲しいです。)

**Comment by K-PTL** [comment]
issue #19 がありましたね、、すみません見落としていました、しかし今さっきinstallしたところなのですが、この問題は現行版では改善されておりませんでした。

**Comment by yoshinobc** [comment]
Thanks for installing it.
We are in the process of submitting an update for https://github.com/yoshinobc/DeepL-Translator-for-PDF/issues/19 to the chrome store.
The latest version will probably be available in the next few hours or days.
If you want to use it right away, we recommend unpacking the zip file in the repository and installing it from chrome:// extensions
In the new version, this problem should not occur except when there is too much text for the screen size, but if you still have a problem, It would be great if you could tell them.
