### ISSUE TITLE
ローカルのpdfをChromeで開くときに起動してしまう

### ISSUE THREAD

**Issue by kuri8ive** [yoshinobc/PDF-Translator#22]
- やりたいこと
ローカルのpdfをChromeで普通に開く

- 起きるエラー
`ERR_FILE_NOT_FOUND`

- 詳細
ローカルのpdfをChromeに投げたときに毎回このextensionが起動してしまい，
pathの頭にこのextension関連の記述がついてしまうため開けない
```
chrome-extension://dnkjinhmoohpidjdgehjbglmgbngnknl/pdf.js/web%20/%20viewer.html?file=file{$pdfのpath}
```

**Comment by yoshinobc** [comment]
ありがとうございます．
ローカルのPDFを開くためには，右上の本Chrome拡張のアイコンを右クリック→拡張機能を管理→ファイルの URL へのアクセスを許可するにチェックをする必要があります．

しかし，本拡張機能がoffの状態でもファイルへのアクセス権限がないファイルを開こうとすると，本拡張機能が起動してしまうバグがありました．これに関しては，すぐに修正をします．

**Comment by yoshinobc** [comment]
修正しました．
https://github.com/yoshinobc/DeepL-Translator-for-PDF/releases/tag/v2.4.0
